config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"
  mount Ckeditor::Engine => "/ckeditor"
  mount Sidekiq::Web => "/sidekiq"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  devise_scope :user do
    get "/signup", to: "devise/registrations#new", as: :signup
  end
  resources :activities, only: [:index]
  resources :cart_items
  resources :orders
  resources :users do
    resources :favorite_books, only: [:index]
  end
  resources :emotions, only: [:destroy, :create]
  resources :blogs
  resources :books, only: [:index, :show]
  resources :emotions, only: [:destroy, :create]
  resources :authors, only: [:index]
  namespace :admin do
    resources :books
    resources :users, except: [:edit]
    resources :authors, only: [:index]
    resources :xmls, only: [:index]
  end
  resources :books do
    resources :comments
    collection {post :search, to: "books#index"}
  end

end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments
  has_many :likes_from_users, class_name: Emotion.name, as: :recipent, dependent: :destroy
  has_many :users_liked, through: :likes_from_users, source: :user
  has_many :cart_items, dependent: :destroy
  has_many :users_added_to_cart, through: :cart_items, source: :user, dependent: :destroy
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books
  belongs_to :category
  mount_uploader :image, PictureUploader

  scope :order_by_created, -> {order created_at: :desc}
  scope :most_liked, -> { order(like: :desc).limit(15) }
  scope :select_book, -> {select :id, :title, :price, :description}
  scope :search_by_title, (lambda do |title|
    where("title LIKE ?", "%#{title}%") unless title.nil?
  end)
  scope :filter_by_book_type, -> category_name {Book.includes(:category)
    .where(categories: {name: category_name}) unless category_name.nil?}

  def self.to_xls(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |book|
        csv << book.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :load_book, only: %i(edit update)
  before_action :load_categories, :load_authors, only: %i(new edit)

  def index
    @books = Book.order_by_created.search(params[:search]).page(params[:page])
      .per Settings.book.per_page
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    @book.author_ids = params[:book][:author_ids]

    if @book.save
      flash[:success] = t ".created_success"
      redirect_to admin_books_path
    else
      flash[:danger] = t ".created_fail"
      render :new
    end
  end

  def edit
  end

  def update
    @book.author_ids = params[:book][:author_ids]

    if @book.update book_params
      flash[:success] = t ".updated_success"
      redirect_to admin_books_path
    else
      flash[:danger] = t ".updated_fail"
      render edit
    end
  end

  def destroy
    @book = Book.find_by id: params[:id]
    if @book.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".deleted_fail"
    end
    redirect_to admin_books_url
  end

  private

  def book_params
    params.require(:book).permit :title, :publisher, :price, :quantity_in_store,
      :image, :description, :category_id, :author_ids
  end

  def load_book
    @book = Book.find_by id: params[:id]

    return if @book
    flash[:danger] = t ".book_not_found"
    redirect_to admin_books_url
  end

  def load_categories
    @categories = Category.all
  end

  def load_authors
    @authors = Author.select_author
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: :show
  before_action :load_categories, only: :index

  def show
    @comment = Comment.new
    @comments = @book.comments.order_by_created
    @cart_item = CartItem.new
  end

  def index
    @owl_books = Book.most_liked
    @books = Book.order_by_created.filter_by_book_type(params[:category])
      .page(params[:page]).per Settings.book.per_page
    @search = Book.ransack(params[:q])
    @books = @search.result.includes(:category).page(params[:page]).per Settings.book.per_page

    if params[:book_name_search]
      @books = Book.search_by_title(params[:book_name_search]).page(params[:page]).per Settings.book.per_page
      respond_to do |format|
        format.html
        format.js {render :index}
      end
    elsif params[:term]
      @books = Book.search_by_title(params[:term]).page(params[:page]).per(Settings.book.per_page)
      render json: @books.map(&:title)
    end
  end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    @recipent = @book
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_author_fields.html.erb
<fieldset>
  <%= f.label :name, "Author's name" %>
  <%= f.text_field :name, class: "form-control",
    id: "author_name_filter", data: { autocomplete_source: authors_path} %>
  <%= f.label :birthday %>
  <%= f.date_select :birthday, :start_year => 1960, :end_year => Date.current.year,
    :order => [:day, :month, :year] %>
</fieldset>

app/views/admin/books/_book_form.html.erb
 <div class="col-md-6 col-md-offset-3">
  <%= form_for([:admin, @book], html: {multipart: true}) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :publisher %>
    <%= f.text_field :publisher, class: "form-control" %>
    <%= f.label :quantity_in_store %>
    <%= f.text_field :quantity_in_store, class: "form-control" %>
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
    <%= f.fields_for :image_books do |i| %>
      <div class="field">
        <%= i.label :image %><br/>
        <%= i.file_field :image, multiple: true, name: "image_books[image][]", class: "upload-image" %>
      </div>

    <% end %>
    <div id="preview"></div>
    <div class="author-field">
      <%= f.label :authors %><br/>
      <%= f.collection_check_boxes(:author_ids, @authors, :id, :name) do |b| %>
        <%= b.label class: "label-checkbox" do %>
          <%= b.check_box + b.text %>
        <% end %><br/>
      <% end %>
    </div>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
    <div>
      <%= f.label :category %>
      <%= f.select :category_id do %>
        <% @categories.each do |c| -%>
          <%= content_tag :option, c.name, value: c.id %>
        <% end %>
      <% end %>
    </div>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/books/_form.html.erb
<%= f.fields_for :authors do |builder| %>
  <%= render "author_fields", f: builder %>
<% end %>
<%= link_to_add_fields t(".add_author"), f, :authors %>

app/views/admin/books/_results.html.erb
<% @books.each.with_index do |book, index| %>
  <tr>
    <td class="text-c">
      <% params[:page] ||= Settings.admin.book.page_index %>
      <%= index_for params[:page], index, Settings.book.per_page %>
    </td>
    <td class="text-c"><%= image_tag book.image.url, :size => Settings.admin.book.image_size %> </td>
    <td class="text-c"><%= book.title %></td>
    <td class="text-c">
      <% book.authors.each do|author| %>
        <%= author.name %>
      <% end %>
    </td>
    <td class="text-c"><%= book.publisher %></td>
    <td class="text-c"><%= book.category.name %></td>
    <td class="text-c"><%= book.price %></td>
    <td class="text-c"><%= book.quantity_in_store %></td>
    <td class="text-c"><%= book.description %></td>
    <td class="text-c">
      <%= link_to raw("<span class='glyphicon glyphicon-trash
            text-danger'></span>"), [:admin, book], method: :delete,
            data: {confirm: t(".confirm_delete")} %>
    </td>
    <td class="text-c"><%= link_to t(".update"), edit_admin_book_path(book) %></td>
  </tr>
<% end %>

app/views/admin/books/_search-results.js.erb
$("#books-table").hide();
$("#search-results").html("<%= j render 'admin/books/results' %>");

app/views/admin/books/edit.html.erb
<% provide :title, t(".edit_book") %>
<% provide :button_text, t(".save") %>
<h1><%= t(".edit_book") %></h1>
<div class="row">
  <%= render "book_form" %>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t(".allbook") %>
<h1><%= t ".allbook" %></h1>
<div>
  <%= form_tag(admin_books_path, method: :get, remote: true) do %>
  <div class="row">
    <div class="form-group col-xs-6 col-md-4">
      <%= text_field_tag :search, params[:search], class: "form-control",
      placeholder: t(".search_title") %>
    </div>
      <%= submit_tag t(".search"), class: "btn btn-primary btn-search-book" %>
      <%= link_to "Add book", new_admin_book_path, class: "btn btn-primary btn-add-book" %>
  </div>
  <% end %>
  <div id="books-table">
    <table class="table table-hover bg-table ls-books">
      <thead class="title_table">
        <tr>
          <th class="text-c"><%= t ".index" %></th>
          <th class="text-c"><%= t ".image" %></th>
          <th class="text-c"><%= t ".title" %></th>
          <th class="text-c"><%= t ".author" %></th>
          <th class="text-c"><%= t ".publisher" %></th>
          <th class="text-c"><%= t ".category" %></th>
          <th class="text-c"><%= t ".price" %></th>
          <th class="text-c"><%= t ".quantity" %></th>
          <th class="text-c"><%= t ".description" %></th>
          <th class="text-c"><%= t ".delete" %></th>
          <th class="text-c"><%= t ".update" %></th>
        </tr>
      </thead>
      <tbody class="result-search">
        <%= render "results" %>
      </tbody>
    </table>
  </div>

    <div class="container">
    <p>
      <%= t ".download" %>
      <%= link_to t(".export_excel"), admin_xmls_path(format: "xls") %>
    </p>
  </div>

  <div class="paginator">
    <%= paginate @books, theme: "twitter-bootstrap-3" %>
  </div>
</div>

app/views/admin/books/index.js.erb
$('.result-search').html('<%= j render "results" %>')
$('.paginator').html('<%= j paginate @books, theme: "twitter-bootstrap-3"%>')

app/views/admin/books/new.html.erb
<% provide :title, t(".addbook") %>
<h1><%= "Add book" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for [:admin, @book] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.label :publisher %>
    <%= f.text_field :publisher, class: "form-control" %>
    <%= f.label :quantity_in_store %>
    <%= f.text_field :quantity_in_store, class: "form-control" %>
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
    <div class="field">
      <%= f.label :image do %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
      <% end %>
    </div>
    <%= render "form", f: f %>
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
    <%= f.label :category %>
    <%= f.select(:category_id) do %>
      <% @categories.each do |c| -%>
        <%= content_tag(:option, c.name, value: c.id) %>
      <% end %>
    <% end %>
    <%= f.submit t(".save"), class: "btn btn-primary" %>
  <% end %>
  </div>
</div>