config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"
  mount Ckeditor::Engine => "/ckeditor"
  mount Sidekiq::Web => "/sidekiq"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  devise_scope :user do
    get "/signup", to: "devise/registrations#new", as: :signup
  end
  resources :activities, only: [:index]
  resources :cart_items
  resources :orders
  resources :users do
    resources :favorite_books, only: [:index]
  end
  resources :emotions, only: [:destroy, :create]
  resources :blogs
  resources :books, only: [:index, :show]
  resources :emotions, only: [:destroy, :create]
  resources :authors, only: [:index]
  namespace :admin do
    resources :books
    resources :users, except: [:edit]
    resources :authors, only: [:index]
    resources :xmls, only: [:index]
  end
  resources :books do
    resources :comments
    collection {post :search, to: "books#index"}
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :content, presence: true

  scope :order_by_created, -> {order created_at: :desc}
  delegate :name, :to => :user, :prefix => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @book = Book.find_by id: params[:book_id]
    @comment = @book.comments.build comment_params
    @comment.user_id = current_user.id
    if @comment.save
      render json: {
        status: :success,
        content: render_to_string(partial: "comments/comment", locals:{comment: @comment})
      }
    end
  end

  def destroy
    @book = Book.find_by id: params[:book_id]
    @comment = Comment.find_by id: params[:id]

    unless @comment.destroy
      flash[:danger] = t ".deleted_fail"
    end
    respond_to do |format|
      format.html { redirect_to @book }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :book_id, :user_id)
  end
end

app/views/comments/_blogs_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag comment.user.avatar.url, size: Settings.user.avatar_comment,
        class: "img-responsive user-photo" %>
    </div>
  </div>
  <div class="col-sm-6 comment-show">
    <div class="panel panel-default panel-custom">
      <div class="panel-heading">
        <strong><%= comment.user_name %></strong>
        <span class="text-muted">
          <%= t ".post" %> <%= time_ago_in_words(comment.created_at) %> <%= t ".ago" %>
        </span>
      </div>
      <div class="panel-body">
        <%= comment.content %>
        <% if current_user?(comment.user) %>
        <%= link_to t(".delete"), blog_comment_path(@recipent, comment),
          method: :delete, data: {confirm: I18n.t("comments.destroy.sure")},
            remote: true, class: "delete-comment" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag comment.user.avatar.url, :size => Settings.user.avatar_comment,
        class: "img-responsive user-photo" %>
    </div>
  </div>
  <div class="col-sm-6 comment-show">
    <div class="panel panel-default panel-custom">
      <div class="panel-heading">
        <strong><%= comment.user_name %></strong>
        <span class="text-muted">
          <%= t ".post" %> <%= time_ago_in_words(comment.created_at) %> <%= t ".ago" %>
        </span>
      </div>
      <div class="panel-body">
        <%= comment.content %>
        <% if current_user?(comment.user) %>
        <%= link_to t(".delete"), book_comment_path(@book, comment),
          method: :delete, data: {confirm: I18n.t("comments.destroy.sure")},
            remote: true, class: "delete-comment" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@book, @comment] do |f| %>
  <%= f.text_field :content, class: "form-control", :placeholder => t(".add_comment") %>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= f.submit t(".comment"), class: "btn-comment" %>
<% end %>

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();
$("#flash_message").html("<%= j render('layouts/flash_message') %>");