config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"
  mount Ckeditor::Engine => "/ckeditor"
  mount Sidekiq::Web => "/sidekiq"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  devise_scope :user do
    get "/signup", to: "devise/registrations#new", as: :signup
  end
  resources :activities, only: [:index]
  resources :cart_items
  resources :orders
  resources :users do
    resources :favorite_books, only: [:index]
  end
  resources :emotions, only: [:destroy, :create]
  resources :blogs
  resources :books, only: [:index, :show]
  resources :emotions, only: [:destroy, :create]
  resources :authors, only: [:index]
  namespace :admin do
    resources :books
    resources :users, except: [:edit]
    resources :authors, only: [:index]
    resources :xmls, only: [:index]
  end
  resources :books do
    resources :comments
    collection {post :search, to: "books#index"}
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i(google_oauth2)
  scope :created_at, -> {order created_at: :desc}
  scope :select_users, -> {select :name, :dob, :email, :address, :avatar, :id}
  scope :order_by_dob, -> {order :dob}
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  mount_uploader :avatar, PictureUploader
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes_for_book, class_name: Emotion.name, dependent: :destroy
  has_many :favorite_books, through: :likes_for_book, source: :recipent, source_type: "Book", dependent: :destroy
  has_many :likes_for_blog, class_name: Emotion.name, dependent: :destroy
  has_many :favorite_blogs, through: :likes_for_blog, source: :recipent, source_type: "Blog", dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :books_in_cart, through: :cart_items, source: :book, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :payment
  enum role: %i{member admin guest}

  def cart_total
    total = 0
    self.cart_items.each { |item| total += item.paideach * item.quantity }
    return total
  end

  def add_to_cart book
    books_in_cart << book
  end

  def delete_from_cart book
    books_in_cart.delete(book)
  end

  def favorite_recipents recipent
    if recipent.class.to_s == "Book"
      favorite_books
    else favorite_blogs
    end
  end

  def likes_for_recipent recipent
    if recipent.class.to_s == "Book"
      likes_for_book
    else likes_for_blog
    end
  end

  def like recipent
    favorite_recipents(recipent) << recipent
    recipent.update_attributes like: recipent.like + 1
  end

  def unlike recipent
    favorite_recipents(recipent).delete recipent
    recipent.update_attributes like: recipent.like - 1
  end

  def liked? recipent
    favorite_recipents(recipent).include?(recipent)
  end

  class << self
    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.avatar = auth.info.image
        user.payment_id = 1
      end
    end

    def new_with_session params, session
      super.tap do |user|
        if data = session["devise.google_data"] &&
          session["devise.google_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action {flash.clear}

  def index
    @users = User.select_users.created_at.page(params[:page]).per(Settings.admin.book.per_page)
  end

  def destroy
    user = User.find_by id: params[:id]

    if user.is_admin?
      flash[:danger] = t ".cant"
    else
      flash[:success] = t ".success"
      User.delete(user)
    end
    @users = User.select_users.created_at.page(params[:page]).per(Settings.admin.book.per_page)
    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.js
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    generic_callback :google
  end

  def generic_callback provider
    @identity = User.from_omniauth(request.env["omniauth.auth"])
    @user = @identity || current_user
    if @user.persisted?
      set_flash_message :notice, :success, kind: provider.capitalize if
        is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(create new)
  before_action :get_payments, except: :show
  before_action :authenticate_user!, only: %i(show edit update)
  before_action :correct_user, only: %i(edit update)

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = t ".created_sucess"
      redirect_to root_url
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def show
    @payments = Payment.all
  end

  def index
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[:success] = t ".updated_success"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
  end

  def index
    @books = @user.favorite_books.paginate page: params[:page] , per_page: Settings.admin.user.per_page
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation,
      :phone_number, :dob, :address, :avatar, :payment_id
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t ".user_not_found"
    redirect_to root_url
  end

  def get_payments
    @payments = Payment.all
    @blogs_notification = Blog.blogs_were_liked(current_user.id)
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user? @user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def payment_collection
    Payment.select_payments
  end

  def current_user? user
    user == current_user
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email, class: "form-label" %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password, class: "form-label" %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirm, class: "form-label" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.label :birthday, class: "form-label" %>
  <%= f.date_select :dob, :start_year => 1960, :end_year => Date.current.year,
    order: %i(day month year), class: "form-control" %>
  <%= f.label :phone_number, class: "form-label" %>
  <%= f.text_field :phone_number, class: "form-control" %>
  <%= f.label :address, class: "form-label" %>
  <%= f.text_field :address, class: "form-control" %>
  <%= f.label :payment, class: "form-label" %>
  <%= f.select :payment_id do %>
    <% @payments.each do |p| %>
      <%= content_tag(:option, p.payment_type, value: p.id) %>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.label :avatar, class: "form-label" do %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
    <% end %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, t(".update_title") %>
<% provide :button_text, t(".update_button") %>
<h1><%= t ".update_profile" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="kenh14-border" id="blog-title" >
<h1><%=(t ".favorite_books")%></h1>
</div>
<div class="row">
<% @books.each do |book| %>
  <div class="col-lg-4 col-md-4 mb-4">
    <div class="card-book h-100">
      <%= link_to image_tag( book.image , size: "120x140", alt: "Ko hien thi"), book_path(book)%>
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to book.title, book_path(book) %>
          </h4>
          <h5><%=book.price.to_s%>đ</h5>
          </div>
          <div class="card-footer">
        </div>
      </div>
    </div>
<% end %>
</div>
<%= will_paginate @books %>

app/views/users/new.html.erb
<% provide :title, t(".signup_title") %>
<% provide :button_text, t(".create_button") %>
<h1 class="logsign"><%= t(".signup_title") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<h2 class="logsign" class="myprofile"><%= t ".my_profile" %></h2>

<div class="card">
  <%= image_tag @user.avatar.url, :size => Settings.user.avatar_profile %>
  <h1 class="profile-name"><%= @user.name %></h1>
  <p>
    <%= t ".email" %>
    <%= @user.email %>
  </p>
  <p>
    <%= t ".birthday" %>
    <%= @user.dob.strftime(t(".time_default")) %>
  </p>
  <p>
    <%= t ".phone" %>
    <%= @user.phone_number %>
  </p>
  <p>
    <%= t ".address" %>
    <%= @user.address %>
  </p>
  <p><button class="button-update"><%= link_to t(".update_button"),  edit_user_path %></button></p>
</div>

app/views/users/update.js.erb
$("#flash_message").html("<%= j (render('layouts/flash_message')) %>")