config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "books#index"
  mount Ckeditor::Engine => "/ckeditor"
  mount Sidekiq::Web => "/sidekiq"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  devise_scope :user do
    get "/signup", to: "devise/registrations#new", as: :signup
  end
  resources :activities, only: [:index]
  resources :cart_items
  resources :orders
  resources :users do
    resources :favorite_books, only: [:index]
  end
  resources :emotions, only: [:destroy, :create]
  resources :blogs
  resources :books, only: [:index, :show]
  resources :emotions, only: [:destroy, :create]
  resources :authors, only: [:index]
  namespace :admin do
    resources :books
    resources :users, except: [:edit]
    resources :authors, only: [:index]
    resources :xmls, only: [:index]
  end
  resources :books do
    resources :comments
    collection {post :search, to: "books#index"}
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action {flash.clear}
  def index
    @items = current_user.cart_items.page(params[:page]).per Settings.admin.book.per_page
    @payments = Payment.all
  end

  def destroy
    current_user.cart_items.find_by(params[:id]).delete
    @items = current_user.cart_items.page(params[:page]).per Settings.admin.book.per_page
    flash[:success] = t ".success"
    respond_to do |format|
      format.html { redirect_to cart_items_path }
      format.js
    end
  end

  def create
    @cart_item = CartItem.new cart_item_params
    @item = CartItem.find_by book_id: cart_item_params[:book_id]
    if @item
      @item.update_attributes cart_item_params
      flash[:success] = t ".update"
    else
      @cart_item.save
      flash[:success] = t ".add"
    end
    respond_to do |format|
      format.html { redirect_to book_path(@book) }
      format.js
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit :book_id, :user_id, :quantity, :paideach
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart.html.erb
<div id="cart">
<table class="table table-hover bg-table ls-books">
  <thead class="title_table">
    <tr>
      <th class="text-c"><%= t ".index" %></th>
      <th class="text-c"><%= t ".image" %></th>
      <th class="text-c"><%= t ".title" %></th>
      <th class="text-c"><%= t ".price" %></th>
      <th class="text-c"><%= t ".quantity" %></th>
      <th class="text-c"><%= t ".delete_item" %></th>
    </tr>
  </thead>
  <tbody>
  <% @items.each_with_index do |item, index| %>
    <tr>
      <td class="text-c">
        <%= index_for params[:page], index, Settings.admin.book.per_page %>
      </td>
      <td class="text-c"><%= link_to image_tag(item.book.image.url, :size => Settings.admin.book.image_size) , book_path(item.book) %></td>
      <td class="text-c"><%= link_to item.book.title, book_path(item.book) %> </td>
      <td class="price"><h4><%= number_to_currency item.paideach, locale: :vi %></h4></td>
      <td class="text-c"><%= item.quantity %></td>
      <td class="text-c">
        <%= link_to raw("<span class='glyphicon glyphicon-trash
          text-danger'></span>"), cart_item_path(item) , method: :delete,
          data: {confirm: t(".confirm_delete")}, remote: true %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>
<table class="table table-hover bg-table ls-books">
  <tbody>
    <tr>
      <td id="total">
        <h4><%= t(".total", vnd: number_to_currency(current_user.cart_total, locale: :vi)) %></h4>
      </td>
    </tr>
  </tbody>
</table>
</div>

app/views/cart_items/create.js.erb
$("#flash_message").html("<%= j render('layouts/flash_message') %>")
$("#menu-button").html("<%= j render('layouts/menu_button') %>")

app/views/cart_items/destroy.js.erb
$("#flash_message").html("<%= j(render('layouts/flash_message')) %>")
$("#menu-button").html("<%= j render('layouts/menu_button') %>")
$("#cart").html("<%= j render('cart_items/cart') %>")

app/views/cart_items/index.html.erb
<% provide(:title, (t ".title"))%>
<div class="kenh14-border" id="blog-title" >
<h1><%=(t ".title")%></h1>
</div>
<div id="books-table">
<%= render "cart" %>
<table class="table table-hover bg-table ls-books">
  <tr>
    <td> <%= link_to (fa_icon t(".cart"), text: t(".add")) , root_path, class: "btn btn-primary" %>
    </td>
    <td> <%= link_to (fa_icon t(".times"), text: t(".delete_all")) , root_path, class: "btn btn-danger" %>
    </td>
    <td> <%= link_to (fa_icon t(".money"), text: t(".checkout")) , new_order_path , class: "btn btn-warning" %>
    </td>
  </tr>
</table>
</div>
<%= paginate @items, theme: "twitter-bootstrap-3" %>